In [1]:
import numpy as np 
import pandas as pd 
import torch 
import torch.nn as nn

In [2]:
class Model(nn.Module):
    def __init__(self, num_features):

        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid() 
    def forward(self, features):
        return self.sigmoid(self.linear(features))

In [3]:
#create dataset 
features = torch.randn(10,5)

#Create model
model = Model(features.shape[1])

# call  model for farward pass
model(features)

tensor([[0.3141],
        [0.4312],
        [0.4327],
        [0.4530],
        [0.5180],
        [0.5082],
        [0.3169],
        [0.3268],
        [0.3182],
        [0.4755]], grad_fn=<SigmoidBackward0>)

In [4]:
# show model weights
model.linear.weight

Parameter containing:
tensor([[-0.4333,  0.0965, -0.1896,  0.0262, -0.1186]], requires_grad=True)

In [5]:
# show model bias
model.linear.bias

Parameter containing:
tensor([-0.3551], requires_grad=True)

In [6]:
!pip install torchinfo  

In [7]:
from torchinfo import summary

summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00